// src/scripts/views/Map.jsx
import { h, Component } from 'preact';

export default class MapView extends Component {
    data(){
        return {
            tiles:[],
            width:32,
            height:32,
            offset:{
                x:0,
                y:0
            }
        }
    }
    render(){
        return <canvas></canvas>;
    }
}

// src/scripts/views/Map.vue
<style>
</style>
<template>
</template>
<script>
import Vue from 'vue';

export default class MapView extends Vue{
    data(){
        return {
            tiles:[],
            width:32,
            height:32,
            offset:{
                x:0,
                y:0
            }
        }
    }
    template(){

    }
}

</script>
